#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MasonX-Request-ExtendedCompRoot
version:      0.03
version_from: lib/MasonX/Request/ExtendedCompRoot.pm
installdirs:  site
requires:
    HTML::Mason:                   1.24

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
